CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    isbn VARCHAR(32) NOT NULL,
    total_copies INTEGER NOT NULL,
    available_copies INTEGER NOT NULL,
    CONSTRAINT books_isbn_unique UNIQUE (isbn),
    CONSTRAINT books_total_copies_non_negative CHECK (total_copies >= 0),
    CONSTRAINT books_available_copies_non_negative CHECK (available_copies >= 0),
    CONSTRAINT books_available_not_above_total CHECK (available_copies <= total_copies)
);

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    CONSTRAINT members_email_unique UNIQUE (email)
);

CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES books (id),
    member_id BIGINT NOT NULL REFERENCES members (id),
    borrowed_at TIMESTAMPTZ NOT NULL,
    due_date TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ,
    CONSTRAINT loans_returned_after_borrow CHECK (returned_at IS NULL OR returned_at >= borrowed_at)
);

CREATE INDEX loans_member_returned_idx ON loans (member_id, returned_at);
CREATE INDEX loans_due_date_idx ON loans (due_date);
